
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./src/components/lending/header";
import MerkleLoader from "./src/components/shared/intro";
import { BackgroundGlow } from "./src/components/shared/background-glow";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-hidden h-screen`}
    >
      <body className="min-h-full relative flex flex-col">
        <Header/>
        {children}
        <MerkleLoader/>
        <BackgroundGlow/>
      </body>
    </html>
  );
}
