
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./src/components/lending/header";
import { ArgusGraph } from "./src/components/lending/graph";
import MerkleLoader from "./src/components/shared/intro";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}  antialiased overflow-hidden h-screen px-20`}
    >
      <body className="min-h-full relative flex flex-col">
        <Header/>
        {children}
        <MerkleLoader/>

        <div className="absolute right-[-100px] top-[15%] w-[900px] h-[2600px] pointer-events-none opacity-80">
                <ArgusGraph/>
            </div>

            <div className="absolute z-0 w-[350px] h-[350px] rounded-full bottom-[-100px] left-[-200px] blur-[230px] bg-[#C8FF3E]"></div>
            <div className="absolute z-0 w-[310px] h-[310px] rounded-full top-[-100px] right-[-200px] blur-[230px] bg-[#C8FF3E]"></div>
      </body>
    </html>
  );
}
